# Generated by Django 5.1.7 on 2025-11-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_display_name', models.CharField(help_text='Nombre descriptivo del bolso', max_length=255, verbose_name='Nombre del Producto')),
                ('base_colour', models.CharField(help_text='Color principal del bolso', max_length=50, verbose_name='Color Base')),
                ('image', models.URLField(blank=True, help_text='URL de la imagen del producto', max_length=500, null=True, verbose_name='URL de Imagen')),
                ('local_image', models.CharField(blank=True, help_text='Ruta de la imagen local', max_length=255, null=True, verbose_name='Imagen Local')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Bolso',
                'verbose_name_plural': 'Bolsos',
                'ordering': ['product_display_name'],
            },
        ),
    ]
