# Generated by Django 5.1.7 on 2025-11-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolso',
            name='local_image',
            field=models.ImageField(blank=True, help_text='Imagen del bolso', null=True, upload_to='bolsos/', verbose_name='Imagen Local'),
        ),
    ]
